/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bdwalker' at '9/9/16 9:23 AM' with Gradle 2.8
 *
 * @author bdwalker, @date 9/9/16 9:23 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
